# Generated by Django 2.0.1 on 2018-01-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adduser', '0002_auto_20180104_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='id',
        ),
        migrations.AlterField(
            model_name='detail',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
